version: "2"
services:
  boilerplate-api:
    build: .
    environment:
      - NODE_ENV=development
      - PORT=3000
      - is_debug=true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  #   depends_on:
  #     - mongodb

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"